import type { Chat, Message, Call, Status } from "./types"

export const dummyChats: Chat[] = [
  {
    id: "1",
    name: "Alice Johnson",
    avatar: "/placeholder.svg?height=40&width=40",
    isOnline: true,
    lastMessage: "Can we meet tomorrow?",
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    lastMessageSender: "them",
    unreadCount: 2,
    isMuted: false,
    isPinned: true,
    isArchived: false,
    about: "Living life to the fullest",
  },
  {
    id: "2",
    name: "Bob Smith",
    avatar: "/placeholder.svg?height=40&width=40",
    isOnline: false,
    lastMessage: "I'll send you the documents later",
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    lastMessageSender: "me",
    lastMessageStatus: "read",
    unreadCount: 0,
    isMuted: false,
    isPinned: false,
    isArchived: false,
  },
  {
    id: "3",
    name: "Work Group",
    avatar: "/placeholder.svg?height=40&width=40",
    isOnline: false,
    lastMessage: "Meeting at 3pm tomorrow",
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    lastMessageSender: "them",
    unreadCount: 5,
    isMuted: true,
    isPinned: false,
    isArchived: false,
  },
  {
    id: "4",
    name: "Charlie Brown",
    avatar: "/placeholder.svg?height=40&width=40",
    isOnline: true,
    lastMessage: "Thanks for the help!",
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    lastMessageSender: "them",
    unreadCount: 0,
    isMuted: false,
    isPinned: false,
    isArchived: false,
  },
  {
    id: "5",
    name: "Diana Prince",
    avatar: "/placeholder.svg?height=40&width=40",
    isOnline: false,
    lastMessage: "Let's catch up soon",
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    lastMessageSender: "me",
    lastMessageStatus: "delivered",
    unreadCount: 0,
    isMuted: false,
    isPinned: false,
    isArchived: false,
  },
  {
    id: "6",
    name: "Family Group",
    avatar: "/placeholder.svg?height=40&width=40",
    isOnline: false,
    lastMessage: "Mom: Who's bringing dessert?",
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    lastMessageSender: "them",
    unreadCount: 3,
    isMuted: true,
    isPinned: true,
    isArchived: false,
  },
  {
    id: "7",
    name: "Edward Norton",
    avatar: "/placeholder.svg?height=40&width=40",
    isOnline: false,
    lastMessage: "Check out this new movie",
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    lastMessageSender: "them",
    unreadCount: 0,
    isMuted: false,
    isPinned: false,
    isArchived: true,
  },
  {
    id: "8",
    name: "Fiona Gallagher",
    avatar: "/placeholder.svg?height=40&width=40",
    isOnline: true,
    lastMessage: "I'll be there in 10 minutes",
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    lastMessageSender: "me",
    lastMessageStatus: "sent",
    unreadCount: 0,
    isMuted: false,
    isPinned: false,
    isArchived: false,
  },
]

export const dummyMessages: Record<string, Message[]> = {
  "1": [
    {
      id: "1-1",
      sender: "them",
      content: "Hey, how are you doing?",
      timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
      type: "text",
    },
    {
      id: "1-2",
      sender: "me",
      content: "I'm good, thanks! How about you?",
      timestamp: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
      status: "read",
      type: "text",
    },
    {
      id: "1-3",
      sender: "them",
      content: "Doing well! I was wondering if you're free tomorrow?",
      timestamp: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
      type: "text",
    },
    {
      id: "1-4",
      sender: "me",
      content: "I should be free after 2pm. What did you have in mind?",
      timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      status: "read",
      type: "text",
    },
    {
      id: "1-5",
      sender: "them",
      content: "I was thinking we could grab coffee and catch up",
      timestamp: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
      type: "text",
    },
    {
      id: "1-6",
      sender: "them",
      content: "It's been a while since we've seen each other",
      timestamp: new Date(Date.now() - 1000 * 60 * 39).toISOString(),
      type: "text",
    },
    {
      id: "1-7",
      sender: "me",
      content: "That sounds great! Let's meet at the usual place at 3pm?",
      timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      status: "read",
      type: "text",
    },
    {
      id: "1-8",
      sender: "them",
      content: "/placeholder.svg?height=300&width=400",
      caption: "Here's the cafe I was talking about",
      timestamp: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
      type: "image",
    },
    {
      id: "1-9",
      sender: "me",
      content: "Looks nice! I'll see you there tomorrow at 3pm then.",
      timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      status: "read",
      type: "text",
    },
    {
      id: "1-10",
      sender: "them",
      content: "Perfect! Can we meet tomorrow?",
      timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
      type: "text",
    },
    {
      id: "1-11",
      sender: "me",
      content: "",
      timestamp: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
      status: "sending",
      type: "voice",
      duration: 12, // 12 seconds
    },
  ],
  "2": [
    {
      id: "2-1",
      sender: "me",
      content: "Hi Bob, did you get a chance to review the proposal?",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      status: "read",
      type: "text",
    },
    {
      id: "2-2",
      sender: "them",
      content: "Yes, I did. It looks good overall, but I have a few comments.",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1.9).toISOString(),
      type: "text",
    },
    {
      id: "2-3",
      sender: "them",
      content: "project-proposal.pdf",
      fileName: "project-proposal.pdf",
      fileSize: "2.4 MB",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1.8).toISOString(),
      type: "file",
    },
    {
      id: "2-4",
      sender: "them",
      content: "I've added some comments to the document. Can you check them?",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1.7).toISOString(),
      type: "text",
    },
    {
      id: "2-5",
      sender: "me",
      content: "Sure, I'll take a look right away.",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1.5).toISOString(),
      status: "read",
      type: "text",
    },
    {
      id: "2-6",
      sender: "me",
      content: "I've addressed all your comments. I'll send you the updated version soon.",
      timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
      status: "read",
      type: "text",
    },
    {
      id: "2-7",
      sender: "them",
      content: "Great, thanks! When do you think you'll have it ready?",
      timestamp: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
      type: "text",
    },
    {
      id: "2-8",
      sender: "me",
      content: "I should have it done by end of day. I'll send you the documents later.",
      timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      status: "read",
      type: "text",
    },
    {
      id: "2-9",
      sender: "me",
      content: "",
      timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
      status: "delivered",
      type: "location",
      location: {
        latitude: 40.7128,
        longitude: -74.006,
        name: "New York City, NY",
      },
    },
  ],
  "3": [
    {
      id: "3-1",
      sender: "them",
      content: "John: Hi everyone, I'm scheduling a team meeting for this week.",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
      type: "text",
    },
    {
      id: "3-2",
      sender: "them",
      content: "Sarah: I'm available on Tuesday and Thursday afternoon.",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 23).toISOString(),
      type: "text",
    },
    {
      id: "3-3",
      sender: "me",
      content: "I can make it any day except Wednesday.",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
      status: "read",
      type: "text",
    },
    {
      id: "3-4",
      sender: "them",
      content: "Mike: Wednesday works best for me, but I can do Thursday too.",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 21).toISOString(),
      type: "text",
    },
    {
      id: "3-5",
      sender: "them",
      content: "John: Let's do Thursday at 3pm then. I'll send a calendar invite.",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
      type: "text",
    },
    {
      id: "3-6",
      sender: "them",
      content: "Sarah: Sounds good!",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 19).toISOString(),
      type: "text",
    },
    {
      id: "3-7",
      sender: "me",
      content: "Works for me too.",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
      status: "read",
      type: "text",
    },
    {
      id: "3-8",
      sender: "them",
      content: "Mike: 👍",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 17).toISOString(),
      type: "text",
    },
    {
      id: "3-9",
      sender: "them",
      content: "John: Here's the agenda for our meeting.",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
      type: "text",
    },
    {
      id: "3-10",
      sender: "them",
      content: "meeting-agenda.docx",
      fileName: "meeting-agenda.docx",
      fileSize: "1.2 MB",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
      type: "file",
    },
    {
      id: "3-11",
      sender: "them",
      content: "John: Meeting at 3pm tomorrow. Please review the agenda beforehand.",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      type: "text",
    },
  ],
}

export const dummyCallHistory: Call[] = [
  {
    id: "call-1",
    name: "Alice Johnson",
    avatar: "/placeholder.svg?height=40&width=40",
    timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    type: "audio",
    status: "completed",
    direction: "incoming",
    duration: 124, // 2 minutes 4 seconds
  },
  {
    id: "call-2",
    name: "Bob Smith",
    avatar: "/placeholder.svg?height=40&width=40",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    type: "video",
    status: "missed",
    direction: "incoming",
  },
  {
    id: "call-3",
    name: "Charlie Brown",
    avatar: "/placeholder.svg?height=40&width=40",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    type: "audio",
    status: "completed",
    direction: "outgoing",
    duration: 45, // 45 seconds
  },
  {
    id: "call-4",
    name: "Diana Prince",
    avatar: "/placeholder.svg?height=40&width=40",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    type: "video",
    status: "completed",
    direction: "outgoing",
    duration: 305, // 5 minutes 5 seconds
  },
  {
    id: "call-5",
    name: "Edward Norton",
    avatar: "/placeholder.svg?height=40&width=40",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    type: "audio",
    status: "missed",
    direction: "incoming",
  },
  {
    id: "call-6",
    name: "Fiona Gallagher",
    avatar: "/placeholder.svg?height=40&width=40",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    type: "audio",
    status: "rejected",
    direction: "incoming",
  },
  {
    id: "call-7",
    name: "George Harris",
    avatar: "/placeholder.svg?height=40&width=40",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    type: "video",
    status: "completed",
    direction: "outgoing",
    duration: 187, // 3 minutes 7 seconds
  },
]

export const dummyStatuses: Status[] = [
  {
    id: "status-1",
    name: "Alice Johnson",
    avatar: "/placeholder.svg?height=40&width=40",
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    viewed: false,
    items: [
      {
        id: "status-1-1",
        type: "text",
        content: "Having a great day at the beach! ☀️🏖️",
        timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        backgroundColor: "#25D366",
      },
      {
        id: "status-1-2",
        type: "image",
        content: "/placeholder.svg?height=800&width=400",
        caption: "Beautiful sunset",
        timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
      },
    ],
  },
  {
    id: "status-2",
    name: "Bob Smith",
    avatar: "/placeholder.svg?height=40&width=40",
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    viewed: false,
    items: [
      {
        id: "status-2-1",
        type: "image",
        content: "/placeholder.svg?height=800&width=400",
        timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      },
    ],
  },
  {
    id: "status-3",
    name: "Charlie Brown",
    avatar: "/placeholder.svg?height=40&width=40",
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    viewed: false,
    items: [
      {
        id: "status-3-1",
        type: "text",
        content: "Just finished my first marathon! 🏃‍♂️",
        timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
        backgroundColor: "#128C7E",
      },
    ],
  },
  {
    id: "status-4",
    name: "Diana Prince",
    avatar: "/placeholder.svg?height=40&width=40",
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    viewed: true,
    items: [
      {
        id: "status-4-1",
        type: "image",
        content: "/placeholder.svg?height=800&width=400",
        caption: "New haircut!",
        timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
      },
    ],
  },
  {
    id: "status-5",
    name: "Edward Norton",
    avatar: "/placeholder.svg?height=40&width=40",
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    viewed: true,
    items: [
      {
        id: "status-5-1",
        type: "text",
        content: "Working late tonight... need coffee! ☕",
        timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
        backgroundColor: "#075E54",
      },
    ],
  },
  {
    id: "status-6",
    name: "Fiona Gallagher",
    avatar: "/placeholder.svg?height=40&width=40",
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    viewed: true,
    items: [
      {
        id: "status-6-1",
        type: "image",
        content: "/placeholder.svg?height=800&width=400",
        timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
      },
      {
        id: "status-6-2",
        type: "text",
        content: "Best concert ever! 🎵🎸",
        timestamp: new Date(Date.now() - 1000 * 60 * 175).toISOString(),
        backgroundColor: "#34B7F1",
      },
    ],
  },
]
